config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'companies/:id/jobs' => 'companies#job_index', as: :job_index

  resources :categories
  resources :jobs
  resources :dashboard, only: :index
  resources :comments
  resources :contacts
  resources :companies

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :title
  has_many :jobs, dependent: :nullify

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :body
  belongs_to :job, dependent: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :jobs, dependent: :destroy
  has_many :contacts, dependent: :destroy
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :full_name, :position, :email
  belongs_to :company
end

app/models/job.rb
class Job < ApplicationRecord
  validates  :title, :level_of_interest, :city, :category_id, presence: true
  belongs_to :company
  belongs_to :category, optional: true
  has_many   :comments

  def self.sort_by(sort_params)
    if sort_params == 'interest'
      order('level_of_interest desc')
    else
      order('city asc')
    end
  end

  def self.restrict_by_city(city)
    where(city: city)
  end

  def self.number_level_interest
    group(:level_of_interest).count(:id)
  end

  def self.top_companies
    company_hash = group(:company).average(:level_of_interest)
    company_hash.sort_by { |_key, value| -value}[0..2]
  end

  def self.city_by_number
    group(:city).count(:id)
  end

  def self.category_by_number
    group(:category_id).count(:id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  def index
    @categories = Category.all
    @job_counts = Job.category_by_number
  end

  def new
    @category = Category.new
  end

  def create
    if Category.find_by(category_params)
      flash.notice = "Sorry, #{category_params[:title]} already exists!"
      redirect_to new_category_path
    else
      @categories = Category.new(category_params)
      @categories.save
      redirect_to category_path(@categories)
    end
  end

  def show
    @jobs = Job.where(category_id: @category.id)
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to category_path(params[:id])
  end

  def destroy
    Category.destroy(@category.id)
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:title)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.job_id = params[:job_id]
    @comment.save
    redirect_to job_path(params[:job_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :job_id)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def job_index
    @company = Company.find(params[:id])
    @jobs = @company.jobs
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "#{@company.name} added!"
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def show
    @company = Company.find(params[:id])
    @contacts = Contact.new
    @contacts.company_id = @company.id
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      flash[:success] = "#{@company.name} updated!"
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    company = Company.find(params[:id])
    company.destroy

    flash[:success] = "#{company.name} was successfully deleted!"
    redirect_to companies_path
  end


  private

  def company_params
    params.require(:company).permit(:name, :city)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contacts = Contact.new(contact_params)
    @contacts.company_id = params[:company_id]
    @contacts.save
    redirect_to company_path(params[:company_id])
  end

  def edit
    @contacts = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    redirect_to company_path(@contact.company)
  end

  def destroy
    contact = Contact.find(params[:id])
    Contact.destroy(params[:id])
    redirect_to company_path(contact.company)
  end


  private

  def contact_params
    params.require(:contact).permit(:full_name, :position, :email, :company_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @level_of_interest = Job.number_level_interest
    @top_companies = Job.top_companies
    @top_cities = Job.city_by_number
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if params[:sort]
      @jobs = Job.sort_by(params[:sort])
      @title = 'All'
    elsif params[:location]
      @jobs = Job.restrict_by_city(params[:location])
      @title = params[:location]
    else
      @jobs = Job.all
      @title = 'All'
    end
  end

  def new
    @job = Job.new()
    @categories = Category.all
    @companies = Company.all
  end

  def create
    @company = Company.find(job_params[:company_id])
    @job = @company.jobs.new(job_params)
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
    @comment = Comment.new
    @comment.job_id = @job.id
  end

  def edit
    @job = Job.find(params[:id])
    @categories = Category.all
    @companies = Company.all
  end

  def update
    @job.update(job_params)
    redirect_to job_path(params[:id])
  end

  def destroy
    Job.destroy(params[:id])
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :level_of_interest, :city, :category_id, :company_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<div class="level">
  <div class="level-item">
  <h1>Edit <strong><%= @category.title %></strong></h1>
  </div>
</div>

<div class="container is-mobile">
  <div class="notification">
    <%= form_for(@category) do |f| %>
      <ul>
      <% @category.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
      <div class="level-item has-text-centered">
      <p>
        <%= f.label :title %></br>
        <%= f.text_field :title %></br>
        <%= f.submit %>
      </p>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="level">
  <div class="level-item">
  <h1>Job Categories</h1>
  </div>
</div>

<div class="level">
  <div class="level-item">
  <h1><%= link_to 'Create New Category', new_category_path %></h1>
  </div>
</div>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <% @categories.each do |category| %>
  <tr id="category-<%= category.id %>-row">
    <td><%= link_to category.title, category_path(category) %></td>
    <td><%= @job_counts[category.id] ||= 0 %>
    <% if @job_counts[category.id] == 1 %>
      <%= 'Job' %>
    <% else %>
      <%= 'Jobs' %>
    <% end %>
    </td>
    <td> <%= link_to 'Edit', edit_category_path(category.id) %></td>
    <td> <%= link_to 'Delete', category_path(category.id), method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/categories/new.html.erb
<div class="level">
  <div class="level-item">
  <h1> Add New Category </h1>
  </div>
</div>

<div class="container is-mobile">
  <div class="notification">
    <%= form_for(@category) do |f| %>
      <ul>
      <% @category.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
      <div class="level-item has-text-centered">
        <p>
          <%= f.label :title %></br>
          <%= f.text_field :title %></br>
          <%= f.submit %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="level">
  <div class="level-item">
    <h1> Job Category: <strong><%= @category.title %></strong> </h1>
  </div>
</div>

<div class="level">
  <div class="level-item">
    <h1><%= link_to 'Add New Job', new_job_path %></h1>
  </div>
</div>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <tr>
    <th>Title</th>
    <th>Company</th>
    <th>City</th>
    <th>Interest</th>
  </tr>
  <% @jobs.each do |job| %>
  <tr>
    <td><%= link_to job.title, job_path(job) %></td>
    <td><%= link_to job.company.name, company_path(job.company) %></td>
    <td><%= link_to job.city, jobs_path(location: job.city) %></td>
    <td>
      <% job.level_of_interest.times do %>
        <span>&#9733;</span>
      <% end %>
      <% (5 - job.level_of_interest).times do %>
        <span>&#9734;</span>
        <% end %>
    </td>
    <td> <%= link_to 'Edit', edit_job_path(job) %></td>
    <td> <%= link_to 'Delete', job_path(job), method: :delete %></td>
  </tr>
  <% end %>
</table>

app/views/companies/_form.html.erb
<div class="container is-mobile">
  <div class="notification">
    <%= form_for(@company) do |f| %>
      <div class="level-item has-text-centered">
      <p>
        <%= f.label :name %></br>
        <%= f.text_field :name %></br>
        <%= f.submit %>
      </p>
      </div>
    <% end %>
  </div>
</div>

app/views/companies/edit.html.erb
<div class="level">
  <div class="level-item">
  <h1>Edit <strong><%= @company.name %></strong></h1>
  </div>
</div>

<%= render partial: "form" %>

app/views/companies/index.html.erb
<div class="level">
  <div class="level-item">
    <h1><strong>All Companies</strong></h1>
  </div>
</div>

<div class="level">
  <div class="level-item">
    <h1><%= link_to 'Add New Company', new_company_path %></h1>
  </div>
</div>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
    <% @companies.each do |company| %>
    <tr class=company_<%= company.id %>>
      <th><%= link_to company.name, job_index_path(company) %></th>
      <th><%= link_to "Edit", edit_company_path(company) %></th>
      <th><%= link_to "Delete", company_path(company), method: "delete" %></th>
    </tr>
    <% end %>
</table>

app/views/companies/job_index.html.erb
<div class="level">
  <div class="level-item">
  <h1>All Jobs for <strong><%= @company.name %></strong></h1>
  </div>
</div>

<div class="level">
  <div class="level-item">
  <h1><%= link_to 'Add New Job', new_job_path %></h1>
  </div>
</div>

<div class="level">
  <div class="level-item">
    <h1><%= link_to 'Add New Company Contact', company_path(@company) %></h1>
  </div>
</div>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <tr>
    <th>Title</th>
    <th>Company</th>
    <th>City</th>
    <th>Interest</th>
  </tr>
  <% @jobs.each do |job| %>
  <tr>
    <td><%= link_to job.title, job_path(job) %></td>
    <td><%= link_to @company.name, company_path(@company) %></td>
    <td><%= link_to job.city, jobs_path(location: job.city)%></td>
    <td><%= link_to 'Edit', edit_job_path(job)%></td>
    <td><%= link_to 'Delete', job_path(job), method: :delete%></td>
  </tr>
  <% end %>
</table>

app/views/companies/new.html.erb
<div class="level">
  <div class="level-item">
  <h1> Add New Company </h1>
  </div>
</div>

<%= render partial: "form" %>

app/views/companies/show.html.erb
<div class="level">
  <div class="level-item">
  <h1><strong><%= @company.name %></strong></h1>
  </div>
</div>

<div class="container is-mobile">
  <div class="notification">
    <%= form_for @contacts do |f| %>
    <div class="level-item has-text-centered">
      <p>
        <%= hidden_field_tag"company_id", @company.id %>
        <%= f.label "Full Name" %></br>
        <%= f.text_field :full_name %></br>
        <%= f.label :position %></br>
        <%= f.text_field :position %></br>
        <%= f.label :email %></br>
        <%= f.text_field :email %></br>
        <%= f.submit "Save" %>
      </p>
      </div>
    <% end %>
  </div>
</div>

<div class="level">
  <div class="level-item">
  <h3><strong>All Contacts</strong></h3>
  </div>
</div>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <tr>
    <th>Full Name</th>
    <th>Position</th>
    <th>Email</th>
  </tr>
  <% @company.contacts.each do |contact| %>
  <tr>
    <td><%= contact.full_name %></td>
    <td><%= contact.position %></td>
    <td><%= link_to contact.email, contact.email %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact)%></td>
    <td><%= link_to 'Delete', contact_path(contact), method: :delete%></td>
  </tr>
  <% end %>
</table>

app/views/contacts/edit.html.erb
<%= form_for @contacts do |f| %>

<p><%= f.label "Full Name" %>
   <%= f.text_field :full_name %>
</p>
<p><%= f.label :Position %>
   <%= f.text_field :position %>
</p>
<p><%= f.label :email %>
   <%= f.text_field :email %>
</p>
<p><%= f.submit "Save" %>
</p>
<% end %>

app/views/dashboard/index.html.erb
<div class="columns">
  <div class="column"></div>
  <div class="column">
<table class="table">
  <tr class="thead">
    <th>Jobs by Interest</th>
  </tr>
  <% @level_of_interest.each do |key, value| %>
  <tr>
    <td>level: <%= key %></td>
    <td><%= value %> jobs</td>
  </tr>
  <% end %>
</table>
</div>
<div class="column">
  <table class="table">
  <tr class="thead">
    <th>Top Companies by Interest</th>
  </tr>
  <% @top_companies.each do |company| %>
  <tr>
    <td><%= company.first.name %></td>
    <td><%= company.last.to_s %> Stars</td>
  </tr>
  <% end %>
</table>
  </div>

  <div class="column"></div>
</div>

<div class="columns">
  <div class="column is-one-half"></div>

<div class="column is-one-half">

<table class='table'>
<tr class="thead">
      <th>City</th>
      <th>Jobs</th>
    </tr>

  <% @top_cities.each do |key, value| %>
      <tr>
    <td><%= link_to key, jobs_path(location: key) %></td>
    <td><%= value %> Jobs</td>
  </tr>
  <% end %>
</table>

</div>
  <div class="column is-one-quarter"></div>
</div>

app/views/jobs/_form.html.erb
<div class="container is-mobile">
  <div class="notification">
    <%= form_for(@job) do |f| %>
      <div class=" has-text-centered">
      </div>



  <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= link_to "Add New Category", new_category_path, :method => "get" %>
</p>
<p>
  <%= f.label :Category %>
  <%= f.collection_select(:category_id, @categories, :id, :title ) %>
</p>
<p>
<%= f.label :Company %>
  <%= f.collection_select(:company_id, @companies, :id, :name ) %>
</p>
<p>
  <%= f.label :description %>
  <%= f.text_field :description %>
</p>
<p>
  <%= f.label :level_of_interest %>
  <%= f.number_field :level_of_interest %>
</p>
<p>
  <%= f.label :city %>
  <%= f.text_field :city %>
</p>
<p>
  <%= f.submit %>
  </p>
   <% end %>
  </div>
</div>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>


<%= render partial: "form" %>

app/views/jobs/index.html.erb
<div class="columns">
  <div class="column is-one-quarter"></div>
  <div class="column">
    <div class="columns">
      <div class="column is-one-quarter"></div>
      <div class="column is-one-half">
  <h3 class="title is-3 is-centered"> <%= @title %> Jobs</h3>
  <h5 class="title is-5 is-centered"> <%= link_to 'Add New Job', new_job_path %></h5>
      </div>
      <div class="column is-one-quarter"></div>
</div>


  <table class="table ">
  <thead>

    <tr>
      <th>Job</th>
      <th>Company</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= link_to job.title, job_path(job) %></td>
      <td><%= link_to job.company.name, company_path(job.company) %></td>
      <td><%= link_to job.city, jobs_path(location: job.city) %></td>
      <td><%= job.level_of_interest %> Stars</td>
      <td><%= link_to 'Edit', edit_job_path(job)%></td>
      <td><%= link_to 'Delete', job_path(job), method: :delete%></td>
    </tr>
  <% end %>
    <tr>
  </tbody>
  </table>
  </div>

  <div class="column is-one-quarter"></div>
</div>

app/views/jobs/new.html.erb
<%= render partial: "form" %>

app/views/jobs/show.html.erb
<div class="columns">
  <div class="column is-one-third"></div>

<div class="content column is-one-half">

  <h3><%= @job.title %></h3>
<ul>
  <li> Description: <%= @job.description %></li>
  <li>Level of Interest: <%= @job.level_of_interest %></li>
  <li>City: <%= @job.city %></li>
  <li>Company: <%= link_to @job.company.name, company_path(@job.company) %></li>
</ul>
<table class="table">
  <tr>
    <th>Comments</th>
  </tr>
  <% @job.comments.order("created_at desc").each do |comment|  %>
  <tr>
    <td><%= comment.body %></td>
  </tr>
  <% end %>
</table>

<h4> Add a New Comment </h4>
<%= form_for @comment do |f| %>
  <p>
  <%= hidden_field_tag"job_id", @job.id %>
  </p>
  <p>
  <%= f.text_area :body, class: "textarea" %>
  </p>
  <p>
  <%= f.submit %>
  </p>
<% end %>
</div>

  <div class="column is-one-third"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type = "text/css" href = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.css">
  <link rel="stylesheet" type = "text/css" href = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.css.map">
  <link rel="stylesheet" type = "text/css" href = "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
</head>

<div class="level">
  <div class="level-item">
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-menu" id="navMenu">
        <a class="navbar-item" href=<%= dashboard_index_path %>>Dashboard</a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="navMenu">
        <a class="navbar-item" href=<%= categories_path %>>Categories</a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="navMenu">
        <a class="navbar-item" href=<%= companies_path %>>Companies</a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="navMenu">
        <a class="navbar-item" href=<%= jobs_path %>>Jobs</a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
    </nav>
  </div>
</div>

<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<%= yield %>

</body>
</html>